import type { AgentRegistrationManifest, BrowserPlanIdentityProfile, BrowserPlanProfileReservation, BrowserPlanProfileReservationInput, CreateIdentityInput, EmailAddress, Identity, IdentityAsset, IdentityAssetInput, IdentityContactCard, IdentityDocumentSet, IdentityIdentifier, IdentityMachineAssignment, IdentityMachineAssignmentInput, PhoneNumber, ProfileImage, UpdateIdentityInput, VoiceProfile } from "./types.js";
export declare const OPEN_IDENTITIES_SCHEME = "open-identities";
export declare function nowIso(): string;
export declare function createOpenIdentityId(): string;
export declare function createDefaultDocuments(): IdentityDocumentSet;
export declare function normalizeIdentifier(identifier: IdentityIdentifier | string): IdentityIdentifier;
export declare function normalizeEmail(email: EmailAddress | string): EmailAddress;
export declare function normalizePhone(phone: PhoneNumber | string): PhoneNumber;
export declare function createIdentity(input: CreateIdentityInput): Identity;
export declare function updateIdentity(identity: Identity, input: UpdateIdentityInput): Identity;
export declare function normalizePersistedIdentity(identity: Identity): Identity;
export declare function addEmail(identity: Identity, email: EmailAddress | string): Identity;
export declare function addPhone(identity: Identity, phone: PhoneNumber | string): Identity;
export declare function assignMachine(identity: Identity, assignment: IdentityMachineAssignmentInput): Identity;
export declare function reserveBrowserPlanProfile(identity: Identity, reservation: BrowserPlanProfileReservationInput): Identity;
export declare function listIdentityMachineAssignments(identity: Identity, machineId?: string): IdentityMachineAssignment[];
export declare function identityHasMachineAssignment(identity: Identity, machineId: string, purpose?: string): boolean;
export declare function identityToBrowserPlanProfile(identity: Identity, reservation: BrowserPlanProfileReservation): BrowserPlanIdentityProfile;
export declare function listBrowserPlanProfilesForIdentity(identity: Identity, machineId?: string): BrowserPlanIdentityProfile[];
export declare function findPrimaryEmail(identity: Identity): EmailAddress | undefined;
export declare function findPrimaryPhone(identity: Identity): PhoneNumber | undefined;
export declare function identityToContactCard(identity: Identity): IdentityContactCard;
export declare function identityIdentifierToString(identifier: IdentityIdentifier): string;
export declare function publicIdentityIdentifier(identity: Identity): IdentityIdentifier;
export declare function identityToAgentManifest(identity: Identity): AgentRegistrationManifest;
export declare function projectIdentityAsset(asset: IdentityAsset): IdentityAsset;
export declare function projectVoiceProfile(voice: VoiceProfile | undefined): VoiceProfile | undefined;
export declare function projectProfileImage(profileImage: ProfileImage | undefined): ProfileImage | undefined;
export declare function renderIdentityInstructions(identity: Identity): string;
export declare function normalizeIdentityAsset(asset: IdentityAssetInput): IdentityAsset;
export declare function normalizeIdentityAssets(assets: IdentityAssetInput[] | undefined): IdentityAsset[];
export declare function normalizeMachineId(machineId: string): string;
export declare function normalizeMachineAssignment(input: IdentityMachineAssignmentInput): IdentityMachineAssignment;
export declare function normalizeMachineAssignments(assignments: IdentityMachineAssignmentInput[] | undefined): IdentityMachineAssignment[];
export declare function normalizeBrowserPlanProfile(input: BrowserPlanProfileReservationInput, emails: Array<EmailAddress | string>, options: {
    defaultProfileName: string;
}): BrowserPlanProfileReservation;
export declare function normalizeBrowserPlanProfiles(profiles: BrowserPlanProfileReservationInput[] | undefined, emails: Array<EmailAddress | string>, options: {
    defaultProfileName: string;
}): BrowserPlanProfileReservation[];
export declare function normalizeVoiceProfile(input: Partial<VoiceProfile>, existing?: VoiceProfile): VoiceProfile;
export declare function normalizeProfileImage(input: Partial<ProfileImage>, existing?: ProfileImage): ProfileImage;
